
GOOGLE_API_KEY_1 = "AIzaSyDPFqHWkIC20DEHklLqVANgQZuEYBcR02s"
GOOGLE_API_KEY_2 = "AIzaSyDPFqHWkIC20DEHklLqVANgQZuEYBcR02s" # Make sure this line exists!
GOOGLE_API_KEY_3 = "AIzaSyDPFqHWkIC20DEHklLqVANgQZuEYBcR02s"
GOOGLE_API_KEY_4 = "AIzaSyDPFqHWkIC20DEHklLqVANgQZuEYBcR02s"
GOOGLE_API_KEY_5 = "AIzaSyDPFqHWkIC20DEHklLqVANgQZuEYBcR02s"