
GOOGLE_API_KEY_1 = "AIzaSyCY9J3IHPCs0WV_a34xCC5-OVSxI7R3aPk"
GOOGLE_API_KEY_2 = "AIzaSyCY9J3IHPCs0WV_a34xCC5-OVSxI7R3aPk" # Make sure this line exists!
GOOGLE_API_KEY_3 = "AIzaSyCY9J3IHPCs0WV_a34xCC5-OVSxI7R3aPk"
GOOGLE_API_KEY_4 = "AIzaSyCY9J3IHPCs0WV_a34xCC5-OVSxI7R3aPk"
GOOGLE_API_KEY_5 = "AIzaSyCY9J3IHPCs0WV_a34xCC5-OVSxI7R3aPk"